### ISSUE TITLE
Criação de Componentes

### ISSUE THREAD

**Issue by brayanapps** [IFRS-Campus-Restinga/2024-2-Sistema-de-Pendencias#1]

**Comment by brayanapps** [comment]
Header
Footer
Button
Input
Dropdown
Notificação
Icone voltar

**Comment by kayanevieira** [comment]
Header OK
Footer OK
Button OK
Icone voltar OK
Dropdown EM ANDAMENTO
Input EM ANDAMENTO
Notificação - foi feito junto ao header, não há necessidade de componente
